//
//  AppsFlyerConstants.swift
//  Plugin
//
//  Created by Paz Lavi  on 08/07/2021.
//

import Foundation

class AppsFlyerConstants {
    static let AF_APP_ID = "appID"
    static let AF_DEV_KEY = "devKey"
    static let AF_DEBUG = "isDebug"
    static let AF_CONVERSION_LISTENER = "registerConversionListener"
    static let AF_OAOA = "registerConversionListener"
    static let AF_UDL = "registerOnDeepLink"
    static let AF_ATT = "waitForATTUserAuthorization"
    static let AF_EVENT_NAME = "eventName"
    static let AF_EVENT_VALUE = "eventValue"
    static let CONVERSION_CALLBACK = "conversion_callback"
    static let OAOA_CALLBACK = "oaoa_callback"
    static let UDL_CALLBACK = "udl_callback"
    static let AF_BRIDGE_SET = "bridge is set"
    static let AF_CUID = "cuid"
    static let AF_CURRENCY_CODE = "currencyCode"
    static let AF_TOKEN = "token"
    static let AF_RECEIPT_SANDBOX = "useReceiptValidationSandbox"
    static let AF_SANDBOX = "useUninstallSandbox"
    static let AF_ONELINK_ID = "onelinkID"
    static let AF_ONELINK_DOMAIN = "domains"
    static let AF_DEEPLINK_URLS = "urls"
    static let  AF_PATH = "path"
    static let AF_UID = "uid"
    static let AF_ANONYMIZE_USER = "anonymizeUser"
    static let AF_STOP = "stop"
    static let AF_IS_STOP = "isStopped"
    static let AF_FILTERS = "filters"
    static let AF_ADDITIONAL_DATA = "additionalData"
    static let AF_DISABLE_SKAD = "shouldDisable"
    static let AF_HOST_PREFIX = "hostPrefixName"
    static let AF_HOST_POSTFIX = "hostName"
    static let AF_BRAND_DOMAIN = "brandDomain"
    static let AF_CAMPAIGN = "campaign"
    static let AF_CHANNEL = "channel"
    static let AF_REFERRER_NAME = "referrerName"
    static let AF_REFERRER_IMAGE_URL = "referrerImageURL"
    static let AF_ADD_PARAMETERS = "addParameters"
    static let AF_REFERRER_CUSTOMER_ID = "referrerCustomerId"
    static let AF_BASE_DEEPLINK = "baseDeeplink"
    static let AF_LINK_READY = "link"
    static let AF_CURRENCY = "currency"
    static let AF_PRICE = "price"
    static let AF_ADDITIONAL_PARAMETERS = "additionalParameters"
    static let AF_IN_APP_PURCHASE = "inAppPurchase"
    static let AF_TRANSACTION_ID = "transactionId"
    static let AF_FB = "enableFacebookDAL"
    static let AF_PUSH_PAYLOAD = "pushPayload"
    static let AF_MIN_TIME = "minTimeBetweenSessions"
    static let AF_PARAMETERS = "parameters"
    static let AF_CONTAINS = "contains"
    static let AF_LANGUAGE = "language"
    static let AF_EMAILS = "emails"
    static let AF_ENCODE = "encode"
    static let AF_LATITUDE = "latitude"
    static let AF_LONGITUDE = "longitude"
    static let AF_PHONE = "phone"
    static let AF_DEEP_LINK_TIME_OUT = "deepLinkTimeout"
    static let AF_EVENT_PARAMETERS = "eventParameters"
    static let AF_PARTNER_ID = "partnerId"
    static let AF_DATA = "data"

}
