// Writes src/version.ts from package.json's version, so pluginVersion is available inside the
// TS program without importing '../package.json' — that import sits above `rootDir: "src"` in
// tsconfig.json, and (verified against tsc 5.7.3) even where it doesn't hit TS6059, it survives
// verbatim into the emitted ESM output with no Node import attribute, throwing
// ERR_IMPORT_ATTRIBUTE_MISSING for any consumer resolving dist/esm/index.js under Node ESM.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const { version } = JSON.parse(readFileSync(`${root}/package.json`, 'utf8'));
writeFileSync(
  `${root}/src/version.ts`,
  `// Auto-generated by scripts/gen-version.mjs from package.json — do not edit.\nexport const version = ${JSON.stringify(version)};\n`,
);
