name: Build apps with AppsFlyer plugin

on:
  workflow_call:

jobs:
  Build-Capacitor-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x


      - name: Install plugin dependencies
        run: npm install
      - name: Build plugin
        run: npm run build
      - name: install capacitor-appsflyer on an Android app
        run: |
          cd examples/CapacitorReact
          npm install ../../
          npx cap add android
          npm run build
          npx cap sync android
      - name: Build apk
        run: |
          cd examples/CapacitorReact/android
          echo "pwd: $(pwd)"
          gradle wrapper
          echo "ls: $(ls)"
          chmod +x ./gradlew
          ./gradlew wrapper --gradle-version 8.14.3
          ./gradlew clean assembleRelease

  Build-Capacitor-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x

      - name: Install plugin dependencies
        run: npm install
      - name: Build plugin
        run: npm run build
      - name: Verify SPM resolution
        run: swift package resolve
      - name: Install capacitor-appsflyer on an iOS app
        run: |
          cd examples/CapacitorReact
          npm install ../../
          npx cap add ios --packagemanager SPM
          npm run build
          npx cap sync ios
      - name: Build iOS app
        run: |
          cd examples/CapacitorReact/ios/App
          xcodebuild -scheme App \
            -destination 'generic/platform=iOS' \
            -skipPackagePluginValidation \
            CODE_SIGNING_ALLOWED=NO build
