name: Build apps with AppsFlyer plugin

on:
  workflow_call:

jobs:
  Build-Capacitor-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x


      - name: Install plugin dependencies
        run: npm install
      - name: Build plugin
        run: npm run build
      - name: install capacitor-appsflyer on an Android app
        run: |
          cd examples/CapacitorReact
          npm install ../../
          npx cap add android
          npm run build
          npx cap sync android
      - name: Build apk
        run: |
          cd examples/CapacitorReact/android
          echo "pwd: $(pwd)"
          gradle wrapper
          echo "ls: $(ls)"
          chmod +x ./gradlew
          ./gradlew wrapper --gradle-version 8.2
          ./gradlew clean assembleRelease

  # Build-Capacitor-ios:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: install react-native-appsflyer on an iOS app
  #     run: |
  #       cd demos/appsflyer-react-native-app
  #       yarn install --force
  #       yarn add ../../ --save
  #   - name: Install Dependencies
  #     run: |
  #       cd demos/appsflyer-react-native-app/ios
  #       pod install --repo-update

  #   - name: Setup provisioning profile
  #     env:
  #       IOS_KEYS: ${{ secrets.IOS_KEYS }}
  #     run: |
  #       chmod +x .github/workflows/scripts/decryptSecrets.sh
  #       ./.github/workflows/scripts/decryptSecrets.sh
  #   - name: Archive app
  #     run: |
  #       sudo xcode-select --switch /Applications/Xcode_12.5.1.app
  #       chmod +x .github/workflows/scripts/archiveApp.sh
  #       cd demos/appsflyer-react-native-app/ios
  #       ./../../../.github/workflows/scripts/archiveApp.sh
