name: Release plugin to QA
on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'

jobs:

  Build-Sample-Apps:
    if: startsWith(github.head_ref, 'releases/')
    uses: ./.github/workflows/build-apps-workflow.yml
    secrets: inherit

  Deploy-To-QA:
    if: startsWith(github.head_ref, 'releases/')
    needs: [Build-Sample-Apps]
    uses: ./.github/workflows/deploy-to-QA.yml
    secrets: inherit
