name: Release plugin to QA

on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'

#  push:
#    branches:
#      - releases/[0-9]+.x.x/[0-9]+.[0-9]+.x/[0-9]+.[0-9]+.[0-9]+-rc[0-9]+
#    paths-ignore:
#      - '**.md'
#      - '**.yml'
#      - 'examples/**'
#      - 'assets/**'
#      - 'docs/**'

jobs:

  Build-Sample-Apps:
    if: startsWith(github.head_ref, 'Release/')
    uses: ./.github/workflows/build-apps-workflow.yml
    secrets: inherit

  Deploy-To-QA:
    if: startsWith(github.head_ref, 'Release/')
    needs: [Build-Sample-Apps]
    uses: ./.github/workflows/deploy-to-QA.yml
    secrets: inherit
