name: Release plugin to QA

on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'

jobs:
  Print-Ref-Head:
    run: echo "head_ref = ${{github.head_ref}}"
  Build-Sample-Apps:
    if: startsWith(github.head_ref, 'Release/')
    uses: ./.github/workflows/build-apps-workflow.yml
    secrets: inherit

  Deploy-To-QA:
    if: startsWith(github.head_ref, 'Release/')
    needs: [Build-Sample-Apps]
    uses: ./.github/workflows/deploy-to-QA.yml
    secrets: inherit
